#!/bin/bash

gpioset 0 27=0
gpioset 0 21=0


BLINK_PID=""

start_blink() {
    (
        while true; do
            gpioset 0 26=1
            sleep 0.5
            gpioset 0 26=0
            sleep 0.5
        done
    ) &
    BLINK_PID=$!
}

stop_blink() {
    if [ -n "$BLINK_PID" ]; then
        kill "$BLINK_PID" 2>/dev/null
        wait "$BLINK_PID" 2>/dev/null
        BLINK_PID=""
    fi
}

gpioset 0 26=0
start_blink
git stash
git pull
g++ loading.cpp -o load_synth_program -lpigpio -lrt -lpthread
LOADER_COMPILE_STATUS=$?
if [ "$LOADER_COMPILE_STATUS" -ne 0 ]; then
    stop_blink
    gpioset 0 26=0
    exit "$LOADER_COMPILE_STATUS"
fi

sudo ./load_synth_program &
LOADER_PID=$!
stop_blink
gpioset 0 26=1




g++ \
  main.cpp \
  Reverb.cpp \
  font5x7.cpp \
  FFTConvolver.cpp \
  TwoStageFFTConvolver.cpp \
  Utilities.cpp \
  AudioFFT.cpp \
  -o main \
  -O3 -flto -std=c++17 \
  -lportaudio -lpthread -lm -lrtaudio -lasound -lncurses -lpigpio -lrt



sudo kill -9 $LOADER_PID 2>/dev/null
sudo killall pigpiod 2>/dev/null
sudo fuser -k 8888/tcp 2>/dev/null
sudo rm -f /var/run/pigpio.pid
while lsof -i :8888 > /dev/null; do 
    sleep 0.5
    if [ "$(gpioget 0 26)" = "1" ]; then
        gpioset 0 26=0
    else
        gpioset 0 26=1
    fi

done

./clear_screen

sleep 1

gpioset 0 26=0
gpioset 0 21=0
gpioset 0 27=1
