#!/bin/bash
git pull

gpioset 0 26=1
gpioset 0 27=0

sudo ./loading

g++ \
  main.cpp \
  Reverb.cpp \
  font5x7.cpp \
  FFTConvolver.cpp \
  TwoStageFFTConvolver.cpp \
  Utilities.cpp \
  AudioFFT.cpp \
  -o main \
  -O3 -std=c++17 \
  -lportaudio -lpthread -lm -lrtaudio -lasound -lncurses -lpigpio -lrt

sudo ./main

gpioset 0 26=0
gpioset 0 21=0
gpioset 0 27=1