#!/bin/bash
g++ \
  main.cpp \
  Reverb.cpp \
  FFTConvolver.cpp \
  TwoStageFFTConvolver.cpp \
  Utilities.cpp \
  AudioFFT.cpp \
  -o main \
  -O3 -std=c++17 \
  -lportaudio -lpthread -lm -lrtaudio -lasound -lncurses -lgpio -lrt

./main
