#!/bin/bash
sudo apt install python3-pip -y
sudo apt update -y
sudo apt install -y g++ make cmake
sudo apt install -y portaudio19-dev
pip install numpy
pip install pyqtgraph
pip install sounddevice
pip install pyaudio